function [  ] = dtWatevs3(Y)
figure('Position',[300 700 700 650]);
% hold on;
% for i = 1:length(trajectories)
%     tr_i = trajectories{i};
%     x = tr_i(:,1);
%     y = tr_i(:,3);
%     plot(x,y,'LineWidth',2)
% end
% grid on;
% axis([0 50 0 50]);
% xlabel('X')
% ylabel('Y')
% title('Tracks generated by simulator')

hold on;
for i = 1:length(Y)
    meas = Y{i};
    scatter(meas(:,1),meas(:,2),'bx')
end
grid on;
axis([0 50 0 50]);
xlabel('X')
ylabel('Y')
title('Measurements generated by simulator')

end

