function [  ] = dtWatevs4(trajectories)
figure('Position',[300 700 700 650]);
hold on;
for i = 1:length(trajectories)
    tr_i = trajectories{i};
    x = tr_i(:,1);
    y = tr_i(:,3);
    plot(x,y,'LineWidth',2)
end
grid on;
axis([0 50 0 50]);
xlabel('X')
ylabel('Y')
title('Tracks generated by simulator')



end

